services:
  app:
    build: .
    container_name: spaceflix-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: LOCAL
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_SCHEMA: spaceflix
    command: ["npm", "run", "start:prod"]

  db:
    image: mysql:8.0
    container_name: spaceflix-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: spaceflix
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: